#echo "XXXXXXXXX ~/.bash_profile"
#

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

if [ -f ~/.bash_local ]; then
    source ~/.bash_local
fi


# Path to the bash it configuration
export BASH_IT="/Users/tracy/Everything/Startup/bash-it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Load Bash It
source $BASH_IT/bash_it.sh

# Path to the bash it configuration
export MY_BASH_IT="/Users/tracy/Everything/Startup/my-bash-it"

# Load original Bash It
source $BASH_IT/bash_it.sh

# Load my-bash-it
source $MY_BASH_IT/my-bash-it.sh
